[package]
name = "sqlx-lms"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
derive_more = "2.1.0"
minijinja = "2.13.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite" ] }
serde_json = "1.0"
serde = "1.0.228"
